### PR TITLE
use protobufjs.loadSync to ensure schema load timing.

### PR DESCRIPTION
**Pull request by perezd**
I think this would address #35,  @smarigowda, do you have a test environment you can verify this patch with?

### CODE REVIEW

**Comment by jamtur01** [comment]
Okay - I've just tested it. Works for me.

**Comment by jamtur01** [comment]
@perezd Do we want to replace `__dirname` and fix #37 too?

**Comment by perezd** [comment]
I'm not really sure what else it should be, any suggested alternatives?

**Comment by perezd** [comment]
Also honestly, I'm not convinced `__dirname` is an anti-pattern truly in commonjs, so let's merge this and let discussion continue on #37 if alternatives can/should be explored.

**Comment by jamtur01** [comment]
Sounds good to me

**Comment by smarigowda** [comment]
> I think this would address #35, @smarigowda, do you have a test environment you can verify this patch with?

I tested this on my local setup and it is working. I am able to see the event in Riemann log. Thank you.

**Pull request merged**
